
variables:
  IPTVIEW_VERSION : "1.0.1"
  CONTAINER_REGISTRY : $CONTAINER_REGISTRY

stages:          # List of stages for jobs, and their order of execution
  - build

#stages: 
#  - tagging
#
#Tagging from pipeline: 
#  stage: tagging
#  script: 
#    # You can write your pipeline code for build/deploy here
#    - docker info
#  after_script:
#    - apk update && apk add git
#    - git --version
#    - git remote remove origin
#    - git remote add origin https://oauth2:${PERSONAL_ACCESS_TOKEN}@gitlab.com/account-name/project-name
#    - git config user.email <your-gitlab-email_id>
#    - git config user.name <your-gitlab-username>
#    - git tag -a v1.0 -m "Release version 1.0"
#  only: 
#    - master


linux-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    - master
  artifacts:
    paths:
      - packages/
  script:
    - echo "Compiling the code..."
    - scripts/build_linux.sh
    - echo "Compile complete."


windows-job:
    stage: build
    tags:
        - windows
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    only:
        - master
    artifacts:
        paths:
            - packages/
    script:
        - scripts/build_windows.ps1
