
variables:
  IPTVIEW_VERSION : "1.0.1"

stages:          # List of stages for jobs, and their order of execution
  - tagging
  - build

Tagging from pipeline:
  stage: tagging
  script:
    - git --version
    - git remote remove origin
    - git remote add origin https://${GITLAB_USER_LOGIN}:${ACCESS_TOKEN}@${CI_SERVER_NAME}/${GITLAB_USER_LOGIN}/${CI_PROJECT_PATH}
    - cur_version=$(git describe --tags)
    - next_version=$(semver bump patch ${cur_version})
    - git tag -a ${next_version} -m "Release version ${next_version}" --author ${CI_COMMIT_AUTHOR}
    - git push origin --tags
  only:
    - master


linux-job:       # This job runs in the build stage, which runs first.
  stage: build
  timeout: 5h
  tags:
    - linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    - master
  artifacts:
    paths:
      - packages/
  script:
    - echo "Compiling the code..."
    - scripts/build_linux.sh
    - echo "Compile complete."


windows-job:
    stage: build
    timeout: 5h
    tags:
        - windows
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    only:
        - master
    artifacts:
        paths:
            - packages/
    script:
        - scripts/build_windows.ps1
