
variables:
  IPTVIEW_VERSION : "1.0.1"

stages:          # List of stages for jobs, and their order of execution
  - tagging
  - build

Tagging from pipeline:
  stage: tagging
  timeout: 30m
  tags:
    - linux
  script:
    - scripts/bump_version.sh
  only:
    - master


linux-job:       # This job runs in the build stage, which runs first.
  stage: build
  timeout: 5h
  tags:
    - linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    - master
  artifacts:
    paths:
      - packages/
  script:
    - echo "Compiling the code..."
    - scripts/build_linux.sh
    - echo "Compile complete."


windows-job:
    stage: build
    timeout: 5h
    tags:
        - windows
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    only:
        - master
    artifacts:
        paths:
            - packages/
    script:
        - scripts/build_windows.ps1
